CREATE TABLE CLINICA_TEST_SQL;

USE CLINICA_TEST_SQL;

CREATE TABLE Usuario(
	ID INT PRIMARY key auto_increment,
	EMAIL VARCHAR(200) NOT NULL UNIQUE,
	SENHA VARCHAR(200) NOT NULL,
	TIPO_USUARIO INT NOT null
);

CREATE TABLE Paciente(
	ID INT PRIMARY key auto_increment,
	ID_USUARIO INT,
 	NOME VARCHAR(200) NOT NULL,
	CPF CHAR(11) UNIQUE NOT NULL ,
	RG CHAR(9) UNIQUE NOT NULL,
	TELEFONE CHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT null,
	CONSTRAINT fk_paciente_usuario FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID)
);

CREATE TABLE Especialidade(
	ID INT PRIMARY KEY auto_increment ,
	NOME VARCHAR(200) NOT NULL
);

CREATE TABLE Clinica(
    ID INT PRIMARY KEY auto_increment,
    NOME_FANTASIA VARCHAR(200) UNIQUE NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    NUMERO INT NOT NULL,
    CEP CHAR(8) UNIQUE NOT NULL,
    RAZAO_SOCIAL VARCHAR(200) UNIQUE NOT NULL    
);

CREATE TABLE Medico (
	ID INT PRIMARY KEY auto_increment,
	ID_USUARIO INT NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	CRM CHAR(7) NOT NULL,
	ID_CLINICA INT NOT NULL,
	ID_ESPECIALIDADE INT NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID),
	FOREIGN KEY (ID_CLINICA) REFERENCES Clinica(ID),
	FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES Especialidade(ID)
);

CREATE TABLE Consulta (
    ID INT PRIMARY KEY auto_increment,
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    DATA_CONSULTA DATETIME NOT NULL,
    DESCRICAO TEXT,
    STATUS_CONSULTA INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES Medico(ID),
    FOREIGN KEY (ID_PACIENTE) REFERENCES Paciente(ID)
);
